## 38.1.2
### Patch Changes

- auth0\_\_oauth_token\_\_fetch_post: fix: alias auth0\_\_oauth_token\_\_POST\_\_fetch2
- auth0\_\_passwordless_start\_\_fetch_post: fix: alias auth0\_\_passwordless_start\_\_POST\_\_fetch2
- auth0\_\_change_password\_\_fetch_post: fix: alias auth0\_\_change_password\_\_POST\_\_fetch2
- auth0\_\_dbconnections_change_password\_\_fetch_post: fix: alias auth0\_\_dbconnections_change_password\_\_POST\_\_fetch2
- auth0\_\_dbconnections_signup\_\_fetch_get: fix: alias auth0\_\_dbconnections_signup\_\_GET\_\_fetch
- jwks\_\_json\_\_fetch_get: alias jwks\_\_json\_\_GET\_\_fetch2

- - auth0\_\_userinfo\_\_GET\_\_fetch2: aliased by auth0\_\_userinfo\_\_fetch_get
- - auth0\_\_passwordless_start\_\_POST\_\_fetch
- - auth0\_\_passwordless_start\_\_POST\_\_fetch2: aliased by auth0\_\_passwordless_start\_\_fetch_post
- - auth0\_\_userinfo\_\_GET\_\_fetch
- - jwks\_\_json\_\_GET\_\_fetch2: aliased by jwks\_\_json\_\_fetch_get
- - auth0\_\_http\_\_error\_
- arguments: (message?:string, error_o?:argument\_\_auth0\_\_unauthorized\_\_error_o_T):
auth0\_\_unauthorized\_\_error\_
auth0\_\_unauthorized\_\_throw
auth0\_\_bad_gateway_error\_
auth0\_\_bad_gateway\_\_throw
- auth0\_\_oauth_token\_\_fetch\_\_body_T:
auth0\_\_password\_\_oauth_token\_\_fetch\_\_body_T
|auth0\_\_passwordless\_\_oauth_token\_\_fetch\_\_body_T
- - auth0\_\_unauthorized\_\_error_o_T,argument\_\_auth0\_\_unauthorized\_\_error_o_T,auth0\_\_unauthorized\_\_error_o_error_T
- auth0\_\_token\_\_error\_\_logout: error argument:
- - auth0\_\_Authorization\_\_validation_pair\_,auth0\_\_Authorization\_\_validation_pair_T
- - auth0\_\_opened\_\_set
- - auth0\_\_token\_\_clear_T: aliased by clear_auth0_token_T
- - auth0\_\_token\_\_error\_\_set
- - auth0\_\_userinfo_token\_\_set
- - auth0\_\_change_password\_\_opened\_\_set
- auth0\_\_opened\_\_class\_: fix: implementation
- auth0\_\_password\_\_oauth_token\_\_fetch\_\_body_T:
- - auth0\_\_access_token_o_T: aliased by auth0\_\_verified\_\_jwt_token_T
- - auth0\__user_id_: aliased by user_id\_
- auth0\_\_token\_\_json\_\_set: fix: implementation
- auth0\_\_token\_\_json\_\_set: fix: export
- - auth0\_\_token\_\_json\_\_set
- - auth0\_\_opened\_\_class\_
- - auth0\_\_token\_\_error\_
- - auth0\_\_in\_\_token\_
- - auth0\_\_login\_\_opened\_
- - auth0\_\_logout\_\_msg_T: aliased by auth0_logout_msg_T
- - auth0_forgot_password_check_email_opened\_
- - AUTH0_URL\_
- - auth0\_\_logout\_\_msg\_
- - auth0\_\_change_password\_\_opened\_
- auth0\_\_passwordless\_\_oauth_token\_\_fetch\_\_body_T: scope?: 'openid'|'openid profile email'
- - auth0\_\_passwordless_start\_\_fetch_post
- - auth0\_\_password\_\_oauth_token\_\_fetch\_\_body_T
- auth0\_\_oauth_token\_\_fetch\_\_body_T: auth0\_\_password\_\_oauth_token\_\_fetch\_\_body_T|auth0\_\_passwordless\_\_oauth_token\_\_fetch\_\_body_T
- auth0\_\_init: + AUTH0_CLIENT_SECRET\_\_set
- - AUTH0_CLIENT_SECRET\_\_,AUTH0_CLIENT_SECRET\_,AUTH0_CLIENT_SECRET\_\_set
- auth0\_\_passwordless_start\_\_fetch_post: fix: server side call to AUTH0_DOMAIN\_(ctx)/passwordless/start: - window
- - auth0\_\_passwordless_start\_\_fetch_post\_\_body_T: aliased by auth0\_\_passwordless_start\_\_fetch\_\_body_T
- auth0\_\_passwordless_start\_\_fetch_post\_\_body_T:
- import_meta_env\_() instead of process.env
- - auth\_\_userinfo\_,auth0\_\_userinfo\_\_set
- - auth0\_\_userinfo\_\_response_pair\_\_,auth0\_\_userinfo\_\_response_pair\_,auth0\_\_userinfo\_\_response_pair\_\_set
- - AUTH0_CLIENT_ID\_,AUTH0_CLIENT_ID\_\_set
- - auth0\_\_userinfo\_\_set
- auth0\_\_userinfo\_\_: fix: type: Be<ReadableAtom\_<auth0\_\_userinfo_T>>
- - AUTH0_DOMAIN\_
- auth0\_\_userinfo\_\_fetch_get\_\_payload_T: + |string: Unauthorized
- auth0\_\_v2\_\_url\_: fix: circular dependency
- login\_\_auth0\_\_oauth_token\_\_fetch\_\_body_T: + scope?: string
- auth0\_\_userinfo\_\_fetch_get\_\_payload_T: auth0\_\_userinfo_T|auth0\_\_userinfo\_\_fetch_get\_\_error_T
- auth0\_\_userinfo_T: extracted from auth0\_\_userinfo\_\_fetch_get\_\_payload_T
- auth0\_\_userinfo\_\_fetch_get\_\_error_T
- auth0\_\_token\_\_is_valid\_: no auth0\_\_token: fix: returns false
- auth0\_\_userinfo\_\_fetch_get\_\_params_T: auth0_token=>auth0\_\_token
- - auth0\_\_jwt\_\_expiration\__is_valid_
- - auth0\_\_token\_\_is_valid\_
- auth0\_\_oauth_token\_\_fetch_post: return type: Promise<[TokenResponse|Auth0Error, Response]>
- - auth0\_\_userinfo\_\_fetch_get\_\_payload_T: aliased by get_auth0_userinfo_T
- - auth0\_\_userinfo\_\_fetch_get\_\_params_T: aliased by get_auth0_userinfo_params_I
- - auth0\_\_userinfo_o\_\_: aliased by auth0\_\_userinfo_ctx\_\_
- auth0\_\_oauth_token\_\_fetch\_\_body_T: auth0\_\_secret\_\_oauth_token\_\_fetch\_\_body_T|login\_\_auth0\_\_oauth_token\_\_fetch\_\_body_T
- login\_\_auth0\_\_oauth_token\_\_fetch\_\_body_T
- - auth0\_\_secret\_\_oauth_token\_\_fetch\_\_body_T
- - auth0\_\_secret\_\_dbconnections_signup\_\_fetch\_\_body_T
- - auth0\_\_init,auth0\_\_init\_\_props_T
- password_realm\_\_body\_: data argument: auth0\_\_client_id\_\_body_T|password_realm\_\_body_T
- auth0\_\_oauth_token\_\_fetch\_\_body_T = auth0\_\_secret\_\_oauth_token\_\_fetch\_\_body_T|auth0\_\_login_data_T
- auth0\_\_dbconnections_signup\_\_fetch\_\_body_T = auth0\_\_dbconnections_signup\_\_fetch\_\_body_T|auth0\_\_secret\_\_dbconnections_signup\_\_fetch\_\_body_T
- auth0\_\_token\_\_error\_\_logout: argument: error:Auth0Error|TokenResponse|auth0\_\_token\_\_error\_\_logout\_\_param_T
- auth0\_\_token\_\_error_T:
- - auth0\_\_token\_\_error_T aliased by auth0_token_error_T
- name convention updates: auth0_token_json=>auth0\_\_token\_\_json
- fix: export auth0\_\_forgot_password\_\_opened\_\_ as auth0_forgot_password_opened\_\_
- fix: export: auth0\_\_authorization\_\_verify as verify_id_token_header_authorization
- fix: auth0\_\_oauth_token\_\_fetch_get=>auth0\_\_oauth_token\_\_fetch_post,auth0\_\_passwordless_start\_\_fetch_get=>auth0\_\_passwordless_start\_\_fetch_post
- auth0\_\_change_password\_\_fetch=>auth0\_\_change_password\_\_fetch_post
auth0\_\_dbconnections_change_password\_\_fetch=>auth0\_\_dbconnections_change_password\_\_fetch_post
- AUTH0_URL instead of AUTH0_URL\_
- AUTH0_URL\_: async,import in function
- AUTH0_URL\_: fix: import auth0-js/package.json
- AUTH0_URL\_: synchronous function
- auth0_token_error\$\_ alias
- fix: jwt_token_exp\_: jwt_token: return null when raw jwt_token does not have '.' format
- fix: @ctx-core/\\\_ dependencies
- auth0_logout_msg\$\_: fix: subscribe: queueMicrotask to auth0_logout_msg$.$ = null
- auth0_logout: queueMicrotask: auth0_logout_msg\$\_(ctx).\$ = null
- in_auth0_token\$\_: memoizing auth0_token_json instead of running JSON.parse(\$)
- fix: in_auth0_token\$\_: dedupe set of the same token content
- fix: get_auth0_userinfo,post_auth0_auth_change_password,post_auth0_dbconnections_change_password,post_auth0_dbconnections_signup,post_auth0_oauth_token,post_auth0_passwordless_start: headers\_
- feat: + bad_gateway_auth0_error\_,unauthorized_auth0_error\_
- fix: auth0_token_json\$\_: set to null when auth0_token_error\$ changes & is present
∋ fetch_response_pair\_
- fix: auth0_token_json\$\_: listen: set localStorage data
- auth0_token_error\$\_: fix: when auth0_opened changes: set to null
- fix: auth0_opened\$\_: auth0_email\$\_(ctx).subscribe: if auth0_email changes: auth0_opened$.$ = null
- fix: auth0_email\$\_: auth0_userinfo\$ is falsy: null: cannot be undefined
- fix: auth0_opened\$\_: dedupe: auth0_email\$\_(ctx).listen(()=>auth0_opened$.$ = null)
- fix: password_realm_body\_: data argument: assigns to default data as 1st level props
- fix: AUTH0_DOMAIN\$\_: process.env.AUTH0_DOMAIN
- fix: auth0_userinfo\$\_: using waitfor_fibonacci_backoff api
- fix: auth0_token\$\_,in_auth0_token\$\_,validate_auth0_change_password,validate_auth0_password_confirmation: remove false state: null instead
- fix: auth0_change_password_opened\$\_: \$ === 'change_password'
fix: auth0_auth0_login_opened\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\$\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_\$\_:\$ === 'login'
- fix: auth0_token\$\_: window.addEventListener: 'storage': event=>set_auth0_token_json(ctx, event)
- fix: auth0_token\$\_: circular dependency
- fix: clear_auth0_token\_=>clear_auth0_token
- fix: clear_auth0_token_error\_=>clear_auth0_token_error
- fix: verify_access_token_header_authorization\_=>verify_access_token_header_authorization
- fix: verify_id_token_header_authorization\_=>verify_id_token_header_authorization
get_auth0_userinfo
post_auth0_oauth_token\_
- fix: error TS6059: \\\_ is not under 'rootDir': package.json: types: ./dist/index.d.ts
- \\\_.d.ts export
- \\\_\_b: ctx is a map: @ctx-core/object: 22.0.0
- fix: \\\_\_ctx_I.generated
- fix: deploying \\\_.js files
- .gitignore: - \\\_.js
- fix: auth0_token_json\$\be\_: type alias export